# branches to build
branches:
  # whitelist
  only:
    - master

install:
  # Install ninja
  - cmd: |
       set NINJA_VERSION="1.6.0"
       appveyor DownloadFile "https://github.com/ninja-build/ninja/releases/download/v%NINJA_VERSION%/ninja-win.zip"
       cmake -E tar xf "ninja-win.zip"
       cmake -E make_directory "ninja"
       cmake -E rename "ninja.exe" "ninja/ninja.exe"
       set PATH=%cd%\ninja;%PATH%
       
build: Script

build_script:
  - cmd: |
      set BASE_DIR=%cd%
      rem cmake -E make_directory "hardware/keyboardio"
      rmdir "hardware\keyboardio\avr" /s /q
      git clone --recursive https://github.com/keyboardio/Arduino-Boards.git "hardware\keyboardio\avr"
      cd hardware\keyboardio\avr\libraries
      git clone -b %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH% --recursive https://github.com/CapeLeidokos/Leidokos-CMake.git
      cd %BASE_DIR%
      cmake -E make_directory "lcm_build"
      cd lcm_build
      cmake -G Ninja -DKALEIDOSCOPE_DOWNLOAD_ARDUINO=TRUE %BASE_DIR%/hardware/keyboardio/avr/libraries/Leidokos-CMake
      ninja.exe nm_diff
  
notifications:
  - provider: Email
    to:
      - shinynoseglasses@gmail.com
    on_build_failure: true