# branches to build
branches:
  # whitelist
  only:
    - master
    
cache:
  - C:\projects\leidokos-cmake\ninja
  - C:\projects\leidokos-cmake\arduino-1.8.5

install:
  # Install ninja
  - cmd: |
       set NINJA_VERSION="1.8.2"
       if exist "C:\projects\leidokos-cmake\ninja\" set GETNINJA=rem
       %GETNINJA% appveyor DownloadFile "https://github.com/ninja-build/ninja/releases/download/v%NINJA_VERSION%/ninja-win.zip"
       %GETNINJA% cmake -E tar xf "ninja-win.zip"
       %GETNINJA% cmake -E make_directory "ninja"
       %GETNINJA% cmake -E rename "ninja.exe" "ninja/ninja.exe"
       set PATH=%cd%\ninja;%PATH%
       
       rem Under windows, Arduinos's binary directory must be in the 
       rem PATH variable for the compiler to work. Therefore, we cannot
       rem rely on Leidokos-CMake to install Arduino as it is not possible
       rem to change the PATH variable through the CMake configuration process.
       
       if exist "C:\projects\leidokos-cmake\arduino-1.8.5\" set GETARDUINO=rem
       %GETARDUINO% appveyor DownloadFile "http://downloads.arduino.cc/arduino-1.8.5-windows.zip"
       %GETARDUINO% cmake -E tar xf arduino-1.8.5-windows.zip
       set PATH=%cd%\arduino-1.8.5\hardware\tools\avr\bin;%PATH%
       
build: Script

build_script:
  - cmd: |
      set BASE_DIR=%cd%
      rmdir "hardware\keyboardio\avr" /s /q
      git clone --recursive https://github.com/keyboardio/Arduino-Boards.git "hardware\keyboardio\avr"
      cd hardware\keyboardio\avr\libraries
      git clone -b %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH% --recursive https://github.com/CapeLeidokos/Leidokos-CMake.git
      cd %BASE_DIR%
      cmake -E make_directory "lcm_build"
      cd lcm_build
      cmake -G Ninja "-DARDUINO_SDK_PATH=C:/projects/leidokos-cmake/arduino-1.8.5" %BASE_DIR%/hardware/keyboardio/avr/libraries/Leidokos-CMake
      ninja.exe nm_diff
  
notifications:
  - provider: Email
    to:
      - shinynoseglasses@gmail.com
    on_build_failure: true