dist: trusty
sudo: false
os:
  - linux
  - osx
  
# Only test direct pushes to master
#
branches:
  only: 
    - master
    
env:
  global:
    - DEPS_DIR=$HOME/deps \
      ARDUINO_VERSION=1.8.5
    
install: |
    # Install Arduino SDK
    #    
    mkdir -p "${DEPS_DIR}"
    cd "${DEPS_DIR}"
    
    if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    
      mkdir AbC
      cd AbC
      touch cDe.txt
      ls ${DEPS_DIR}/abc/cde.txt
      ls ${DEPS_DIR}/AbC/cDe.tx[t]
      ls '${DEPS_DIR}/abc/cde.tx[t]'
      grealpath ${DEPS_DIR}/abc/cde.txt
      grealpath ${DEPS_DIR}/AbC/cDe.tx[t]
      grealpath '${DEPS_DIR}/abc/cde.tx[t]'
      realpath ${DEPS_DIR}/abc/cde.txt
      realpath ${DEPS_DIR}/AbC/cDe.tx[t]
      realpath '${DEPS_DIR}/abc/cde.tx[t]'
      readlink -f ${DEPS_DIR}/abc/cde.txt
      readlink -f ${DEPS_DIR}/AbC/cDe.tx[t]
      readlink -f '${DEPS_DIR}/abc/cde.tx[t]'
      which ls
      
      cd "${DEPS_DIR}"
    
      export ARDUINO_DIR=${DEPS_DIR}/Arduino.app/Contents/Java
      
      if [ ! -d "${ARDUINO_DIR}" ]; then
         ARDUINO_HOST_PLATFORM="macosx"
         ARDUINO_ARCHIVE="arduino-${ARDUINO_VERSION}-${ARDUINO_HOST_PLATFORM}.zip"
         wget "http://downloads.arduino.cc/${ARDUINO_ARCHIVE}"
         unzip "${ARDUINO_ARCHIVE}"
      fi
    else
    
      export ARDUINO_DIR=${DEPS_DIR}/arduino-${ARDUINO_VERSION}
      
      if [ ! -d "${ARDUINO_DIR}" ]; then
         ARDUINO_HOST_PLATFORM="linux64"
         ARDUINO_ARCHIVE="arduino-${ARDUINO_VERSION}-${ARDUINO_HOST_PLATFORM}.tar.xz"
         wget "http://downloads.arduino.cc/${ARDUINO_ARCHIVE}"
         tar xJf "${ARDUINO_ARCHIVE}"
      fi
    fi
  
script: 
  - cd $HOME
  - mkdir -p hardware/keyboardio
  - git clone --recursive https://github.com/keyboardio/Arduino-Boards.git hardware/keyboardio/avr
  - cd hardware/keyboardio/avr/libraries
  - if [ -n "${TRAVIS_PULL_REQUEST_BRANCH}" ]; then test_branch="${TRAVIS_PULL_REQUEST_BRANCH}"; else test_branch="${TRAVIS_BRANCH}"; fi
  - git clone -b "${test_branch}" --recursive https://github.com/CapeLeidokos/Leidokos-CMake.git
  - cd $HOME
  - mkdir kcm_build
  - cd kcm_build
  - echo "ARDUINO_DIR=${ARDUINO_DIR}"
  - ls ${ARDUINO_DIR}
  - cmake "-DARDUINO_SDK_PATH=${ARDUINO_DIR}" $HOME/hardware/keyboardio/avr/libraries/Leidokos-CMake
  - cmake --build . --target nm_diff
  
notifications:
  email:
    recipients:
      - shinynoseglasses@gmail.com
    on_failure: always
    
cache:
  directories:
    - ${DEPS_DIR}