dist: trusty
sudo: false
os:
  - linux
  - osx
  
# Only test direct pushes to master
#
branches:
  only: 
    - master
    
#before_install:
  #- sudo apt-get -qq update
  #- sudo apt-get install -y cmake
  
script:
  - cd $HOME
  - mkdir -p hardware/keyboardio
  - git clone --recursive https://github.com/keyboardio/Arduino-Boards.git hardware/keyboardio/avr
  - cd hardware/keyboardio/avr/libraries
  - git clone -b ${TRAVIS_BRANCH} --recursive https://github.com/CapeLeidokos/Leidokos-CMake.git
  - cd $HOME
  - mkdir kcm_build
  - cd kcm_build
  - cmake -DKALEIDOSCOPE_DOWNLOAD_ARDUINO=TRUE $HOME/hardware/keyboardio/avr/libraries/Leidokos-CMake
  - make nm_diff
  
notifications:
  email:
    recipients:
      - shinynoseglasses@gmail.com
    on_failure: always
    
cache:
ccache: true